name: Update Rasp

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: git push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          echo "aboba"
          
