name: Update Rasp

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 15 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: run script
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
        run: python update.py 
          
      - name: git push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          cat aboba.txt
